PYTHON = 1
JAVASCRIPT = 2
ALGORITHMS = 3
MACHINELEARNING = 4
OPERATINGSYSTEM = 5
DATABASE = 6
BOOK_TYPES = {
    PYTHON:'python',
    JAVASCRIPT:'Javascript',
    ALGORITHMS:'数据结构与算法',
    MACHINELEARNING:'机器学习',
    OPERATINGSYSTEM:'操作系统',
    DATABASE:'数据库',
}
ONLINE = 1
OFFLINE = 0
STATUS_CHOICE = {
    ONLINE:'上线',
    OFFLINE:'下线',
}